### ISSUE TITLE
lightbulb 0.1d

### ISSUE THREAD

**Issue by lordkylua** [tupleHunden/RoamRoulette#1]
![Screenshot_20221016-075451~2](https://user-images.githubusercontent.com/30421030/196031442-5d38441e-a0c1-4dfb-93c5-73e96b062b93.png)

Hello. I'm having trouble with that dependency. I can't find her anywhere. You can help. Thank you

**Comment by tupleHunden** [comment]
I think you might have to remove that - It should be completed by the other lightbulb entry in requirements.  This was an oversight when generating the requirements.txt

**Comment by tupleHunden** [comment]
Removed this and everything should be good - let me know if it isn't.

**Comment by tupleHunden** [comment]
Double check that the pathing for command files is working correctly, this was built specific to my setup without a lot of testing on other systems.

**Comment by lordkylua** [comment]
![Sin título](https://user-images.githubusercontent.com/30421030/196803412-94120c8d-38cc-41c4-9e49-ba596e2f1a6d.png)
works. but the slash command does not appear in the discord.
the bot does not run well for me.
does not show the commands
